import Head from "next/head";
import QuestionInput from "../components/QuestionComponents/QuestionInput/QuestionInput";
import QuestinoRadio from "../components/QuestionComponents/QuestionRadio/QuestionRadio";
import styles from "@/styles/Question.module.scss";
type PropsType = {
  id: string;
};
//pages/question/[id].tsx
//http://localhost:3000/question/1233    //c端H5的url规则
//http://localhost:3000/question/fodisfnkdbsjoabfjs
export default function Question(props: PropsType) {
  return (
    <>
      <Head>
        <title>Question</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main>
        <h1>Questino Page</h1>
        <p>{props.id}</p>
        <form method="post" action="/api/answer">
          <input type="hidden" name="questionId" defaultValue={props.id} />
          <div className={styles.componentWrapper}>
            <QuestionInput
              fe_id="c1"
              props={{ title: "你的问题", placeholder: "请输入" }}
            />
          </div>
          <div className={styles.componentWrapper}>
            <QuestinoRadio
              fe_id="c2"
              props={{
                title: "你的姓名",
                options: [
                  { value: "male", text: "男" },
                  { value: "female", text: "女" },
                ],
                value: "male",
                isVertical: false,
              }}
            />
          </div>

          <div className={styles.submitBtnContainer}>
            <button type="submit">提交</button>
          </div>
        </form>
      </main>
    </>
  );
}
export async function getServerSideProps(context: any) {
  const { id = "" } = context.params;
  //根据id await 获取问卷数据
  return {
    props: {
      id,
      //其他数据
    },
  };
}
